"use server";

import { redirect } from "next/navigation";
import type { CrmActionState } from "@/app/actions/customers";
import { requireOrganization } from "@/lib/auth/current";
import { createSupabaseServerClient } from "@/lib/supabase/server";

const value = (formData: FormData, name: string) => String(formData.get(name) ?? "").trim();
const duplicatePackageMessage = "A package with this name already exists.";
const duplicateSectionMessage = "This item is already part of this section.";
const isDuplicate = (error: { code?: string | null }) => error.code === "23505";
function optionalNumber(raw: string) { if (!raw) return null; const parsed = Number(raw); return Number.isFinite(parsed) && parsed >= 0 ? String(parsed) : undefined; }

function packageValues(formData: FormData) {
  const name = value(formData, "name"); const basePrice = optionalNumber(value(formData, "base_price")); const budgetMin = optionalNumber(value(formData, "recommended_budget_min")); const budgetMax = optionalNumber(value(formData, "recommended_budget_max")); const displayOrder = Number(value(formData, "display_order") || 0);
  if (!name) return { error: "Package name is required." } as const;
  if (basePrice === null || basePrice === undefined) return { error: "Enter a valid base price." } as const;
  if (budgetMin === undefined || budgetMax === undefined) return { error: "Recommended budgets must be valid numbers." } as const;
  if (budgetMin !== null && budgetMax !== null && Number(budgetMax) < Number(budgetMin)) return { error: "Recommended budget maximum must be at least the minimum." } as const;
  if (!Number.isInteger(displayOrder) || displayOrder < 0) return { error: "Display order must be zero or greater." } as const;
  return { data: { name, description: value(formData, "description") || null, base_price: basePrice, recommended_budget_min: budgetMin, recommended_budget_max: budgetMax, active: formData.get("active") === "on", display_order: displayOrder } } as const;
}

export async function createPackageAction(_state: CrmActionState, formData: FormData): Promise<CrmActionState> { const parsed = packageValues(formData); if ("error" in parsed) return { error: parsed.error }; const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("packages").insert({ ...parsed.data, organization_id: organization.id }).select("id").single(); if (error) return { error: isDuplicate(error) ? duplicatePackageMessage : "We could not create this package." }; if (!data) return { error: "We could not create this package." }; redirect(`/packages/${data.id}?created=1`); }
export async function updatePackageAction(_state: CrmActionState, formData: FormData): Promise<CrmActionState> { const packageId = value(formData, "package_id"); if (!packageId) return { error: "Package information is missing." }; const parsed = packageValues(formData); if ("error" in parsed) return { error: parsed.error }; const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("packages").update({ ...parsed.data, updated_at: new Date().toISOString() }).eq("organization_id", organization.id).eq("id", packageId).select("id").maybeSingle(); if (error) return { error: isDuplicate(error) ? duplicatePackageMessage : "We could not update this package." }; if (!data) return { error: "Package not found." }; redirect(`/packages/${packageId}?updated=1`); }
export async function togglePackageAction(_state: CrmActionState, formData: FormData): Promise<CrmActionState> { const packageId = value(formData, "package_id"); if (!packageId) return { error: "Package information is missing." }; const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient(); const { data: item, error: loadError } = await supabase.from("packages").select("active").eq("organization_id", organization.id).eq("id", packageId).maybeSingle(); if (loadError) return { error: "We could not check this package." }; if (!item) return { error: "Package not found." }; const { error } = await supabase.from("packages").update({ active: !item.active, updated_at: new Date().toISOString() }).eq("organization_id", organization.id).eq("id", packageId); if (error) return { error: "We could not change this package’s status." }; redirect(`/packages/${packageId}?status=${item.active ? "inactive" : "active"}`); }
export async function deletePackageAction(_state: CrmActionState, formData: FormData): Promise<CrmActionState> { const packageId = value(formData, "package_id"); if (!packageId) return { error: "Package information is missing." }; const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient(); const { count, error: checkError } = await supabase.from("quotes").select("id", { count: "exact", head: true }).eq("organization_id", organization.id).eq("package_id", packageId); if (checkError) return { error: "We could not check whether this package is in use." }; if ((count ?? 0) > 0) return { error: "This package is already in use. Deactivate it instead of deleting it." }; const { data, error } = await supabase.from("packages").delete().eq("organization_id", organization.id).eq("id", packageId).select("id").maybeSingle(); if (error) return { error: "We could not delete this package." }; if (!data) return { error: "Package not found." }; redirect("/packages?deleted=1"); }

function packageItemValues(formData: FormData) {
  const packageId = value(formData, "package_id"); const catalogItemId = value(formData, "catalog_item_id"); const quantity = Number(value(formData, "quantity")); const unit = value(formData, "unit"); const type = value(formData, "item_type"); const priceOverride = optionalNumber(value(formData, "price_override"));
  if (!packageId) return { error: "Package information is missing." } as const; if (!catalogItemId) return { error: "Choose a catalog item." } as const; if (!Number.isFinite(quantity) || quantity <= 0) return { error: "Quantity must be greater than zero." } as const; if (!unit) return { error: "Unit is required." } as const; if (!['included', 'addon'].includes(type)) return { error: "Choose included item or optional add-on." } as const; if (priceOverride === undefined) return { error: "Price override must be zero or greater." } as const;
  return { packageId, data: { catalog_item_id: catalogItemId, quantity: String(quantity), unit, included: type === "included", optional_addon: type === "addon", price_override: priceOverride, notes: value(formData, "notes") || null } } as const;
}

async function validatePackageItem(supabase: Awaited<ReturnType<typeof createSupabaseServerClient>>, organizationId: string, packageId: string, catalogItemId: string) {
  const [{ data: packageRow, error: packageError }, { data: catalogItem, error: catalogError }] = await Promise.all([supabase.from("packages").select("id").eq("organization_id", organizationId).eq("id", packageId).maybeSingle(), supabase.from("catalog_items").select("id").eq("organization_id", organizationId).eq("id", catalogItemId).eq("active", true).maybeSingle()]);
  if (packageError || catalogError) return "We could not check this package item."; if (!packageRow) return "Package not found."; if (!catalogItem) return "Choose an active catalog item."; return null;
}

export async function createPackageItemAction(_state: CrmActionState, formData: FormData): Promise<CrmActionState> { const parsed = packageItemValues(formData); if ("error" in parsed) return { error: parsed.error }; const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient(); const validationError = await validatePackageItem(supabase, organization.id, parsed.packageId, parsed.data.catalog_item_id); if (validationError) return { error: validationError }; const { data: duplicate, error: duplicateError } = await supabase.from("package_items").select("id").eq("organization_id", organization.id).eq("package_id", parsed.packageId).eq("catalog_item_id", parsed.data.catalog_item_id).eq("included", parsed.data.included).eq("optional_addon", parsed.data.optional_addon).maybeSingle(); if (duplicateError) return { error: "We could not check this package section." }; if (duplicate) return { error: duplicateSectionMessage }; const { error } = await supabase.from("package_items").insert({ ...parsed.data, organization_id: organization.id, package_id: parsed.packageId }); if (error) return { error: isDuplicate(error) ? duplicateSectionMessage : "We could not add this package item." }; redirect(`/packages/${parsed.packageId}?item=added`); }
export async function updatePackageItemAction(_state: CrmActionState, formData: FormData): Promise<CrmActionState> { const packageItemId = value(formData, "package_item_id"); if (!packageItemId) return { error: "Package item information is missing." }; const parsed = packageItemValues(formData); if ("error" in parsed) return { error: parsed.error }; const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient(); const validationError = await validatePackageItem(supabase, organization.id, parsed.packageId, parsed.data.catalog_item_id); if (validationError) return { error: validationError }; const { data: duplicate, error: duplicateError } = await supabase.from("package_items").select("id").eq("organization_id", organization.id).eq("package_id", parsed.packageId).eq("catalog_item_id", parsed.data.catalog_item_id).eq("included", parsed.data.included).eq("optional_addon", parsed.data.optional_addon).neq("id", packageItemId).maybeSingle(); if (duplicateError) return { error: "We could not check this package section." }; if (duplicate) return { error: duplicateSectionMessage }; const { data, error } = await supabase.from("package_items").update({ ...parsed.data, updated_at: new Date().toISOString() }).eq("organization_id", organization.id).eq("package_id", parsed.packageId).eq("id", packageItemId).select("id").maybeSingle(); if (error) return { error: isDuplicate(error) ? duplicateSectionMessage : "We could not update this package item." }; if (!data) return { error: "Package item not found." }; redirect(`/packages/${parsed.packageId}?item=updated`); }
export async function removePackageItemAction(_state: CrmActionState, formData: FormData): Promise<CrmActionState> { const packageId = value(formData, "package_id"); const packageItemId = value(formData, "package_item_id"); if (!packageId || !packageItemId) return { error: "Package item information is missing." }; const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("package_items").delete().eq("organization_id", organization.id).eq("package_id", packageId).eq("id", packageItemId).select("id").maybeSingle(); if (error) return { error: "We could not remove this package item." }; if (!data) return { error: "Package item not found." }; redirect(`/packages/${packageId}?item=removed`); }

const starterPackages = [
  { name: "Basic Package", description: "A simple roofline package for customers who want a clean holiday look at an entry-level price.", base: 995, min: 900, max: 1300, order: 1, items: [["C9 Warm White Roofline Lights", 125, "ft", true, "Front roofline up to 125 ft"], ["Timer", 1, "each", true, null], ["Takedown Service", 1, "service", true, null], ["36-inch Wreath", 1, "each", false, null], ["Garland", 1, "ft", false, null], ["Walkway Stake Lights", 1, "ft", false, null], ["Storage Service", 1, "service", false, null]] },
  { name: "Classic Package", description: "A popular package that adds more curb appeal with roofline lights, one wreath, and common upgrade options.", base: 1495, min: 1300, max: 2000, order: 2, items: [["C9 Warm White Roofline Lights", 175, "ft", true, "Front roofline and garage/front peak allowance"], ["36-inch Wreath", 1, "each", true, null], ["Timer", 1, "each", true, null], ["Takedown Service", 1, "service", true, null], ["36-inch Wreath", 1, "each", false, "Additional wreath upgrade"], ["Garland", 1, "ft", false, null], ["Walkway Stake Lights", 1, "ft", false, null], ["Bush Lights", 1, "bush", false, null], ["Storage Service", 1, "service", false, null]] },
  { name: "Premium Package", description: "A high-impact holiday package for customers who want a fuller decorated look with roofline lights, wreaths, garland, and walkway lighting.", base: 2495, min: 2000, max: 3500, order: 3, items: [["C9 Warm White Roofline Lights", 250, "ft", true, null], ["36-inch Wreath", 2, "each", true, null], ["Garland", 25, "ft", true, null], ["Walkway Stake Lights", 60, "ft", true, null], ["Timer", 1, "each", true, null], ["Takedown Service", 1, "service", true, null], ["Tree Wrap", 1, "tree", false, null], ["36-inch Wreath", 1, "each", false, "Additional wreath upgrade"], ["Bush Lights", 1, "bush", false, null], ["Storage Service", 1, "service", false, null]] },
] as const;

export async function loadStarterPackagesAction(_state: CrmActionState, _formData: FormData): Promise<CrmActionState> {
  const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient();
  const requiredNames = [...new Set(starterPackages.flatMap((item) => item.items.map((entry) => entry[0])))];
  const { data: catalogRows, error: catalogError } = await supabase.from("catalog_items").select("id, name").eq("organization_id", organization.id);
  if (catalogError) return { error: "We could not check your catalog." };
  const catalog = new Map((catalogRows ?? []).map((item) => [item.name.toLocaleLowerCase(), item.id]));
  if (requiredNames.some((name) => !catalog.has(name.toLocaleLowerCase()))) return { error: "Load your starter catalog before loading starter packages." };
  const { data: existingRows, error: existingError } = await supabase.from("packages").select("id, name").eq("organization_id", organization.id);
  if (existingError) return { error: "We could not check your existing packages." };
  const packagesByName = new Map((existingRows ?? []).map((item) => [item.name.toLocaleLowerCase(), item.id])); let addedPackages = 0;
  for (const starter of starterPackages) { if (packagesByName.has(starter.name.toLocaleLowerCase())) continue; const { data, error } = await supabase.from("packages").insert({ organization_id: organization.id, name: starter.name, description: starter.description, base_price: String(starter.base), recommended_budget_min: String(starter.min), recommended_budget_max: String(starter.max), active: true, display_order: starter.order }).select("id").single(); if (!error && data) { packagesByName.set(starter.name.toLocaleLowerCase(), data.id); addedPackages += 1; continue; } if (!isDuplicate(error ?? {})) return { error: "We could not load starter packages." }; const { data: raced } = await supabase.from("packages").select("id").eq("organization_id", organization.id).ilike("name", starter.name).maybeSingle(); if (!raced) return { error: "We could not finish loading starter packages." }; packagesByName.set(starter.name.toLocaleLowerCase(), raced.id); }
  const packageIds = starterPackages.map((item) => packagesByName.get(item.name.toLocaleLowerCase())).filter((id): id is string => Boolean(id));
  const { data: existingItems, error: itemError } = await supabase.from("package_items").select("package_id, catalog_item_id, included, optional_addon").eq("organization_id", organization.id).in("package_id", packageIds);
  if (itemError) return { error: "We could not check starter package items." };
  const keys = new Set((existingItems ?? []).map((item) => `${item.package_id}|${item.catalog_item_id}|${item.included}|${item.optional_addon}`)); let addedItems = 0;
  for (const starter of starterPackages) { const packageId = packagesByName.get(starter.name.toLocaleLowerCase())!; for (const [name, quantity, unit, included, notes] of starter.items) { const catalogItemId = catalog.get(name.toLocaleLowerCase())!; const key = `${packageId}|${catalogItemId}|${included}|${!included}`; if (keys.has(key)) continue; const { error } = await supabase.from("package_items").insert({ organization_id: organization.id, package_id: packageId, catalog_item_id: catalogItemId, quantity: String(quantity), unit, included, optional_addon: !included, price_override: null, notes }); if (error) return { error: "We could not finish loading starter package items." }; keys.add(key); addedItems += 1; } }
  redirect(`/packages?starter=${addedPackages || addedItems ? "added" : "ready"}&packages=${addedPackages}&items=${addedItems}`);
}
