"use server";

import { redirect } from "next/navigation";
import type { CrmActionState } from "@/app/actions/customers";
import { requireOrganization } from "@/lib/auth/current";
import { paymentMethods, paymentRecordStatuses, paymentTotal, paymentTypes } from "@/lib/payment-options";
import { createSupabaseServerClient } from "@/lib/supabase/server";
const value = (formData: FormData, name: string) => String(formData.get(name) ?? "").trim();
const typeValues = new Set<string>(paymentTypes.map((item) => item.value)); const statusValues = new Set<string>(paymentRecordStatuses.map((item) => item.value)); const methodValues = new Set<string>(paymentMethods);
function paymentValues(formData: FormData) { const type = value(formData, "payment_type"); const amount = Number(value(formData, "amount")); const date = value(formData, "payment_date"); const method = value(formData, "payment_method"); const status = value(formData, "status"); if (!typeValues.has(type)) return { error: "Choose a valid payment type." } as const; if (!Number.isFinite(amount) || amount <= 0) return { error: "Payment amount must be greater than zero." } as const; if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return { error: "Choose a valid payment date." } as const; if (method && !methodValues.has(method)) return { error: "Choose a valid payment method." } as const; if (!statusValues.has(status)) return { error: "Choose a valid payment status." } as const; return { data: { payment_type: type, amount: String(amount), payment_date: `${date}T12:00:00`, payment_method: method || null, reference_number: value(formData, "reference_number") || null, status, notes: value(formData, "notes") || null } } as const; }
async function recalculate(supabase: Awaited<ReturnType<typeof createSupabaseServerClient>>, organizationId: string, jobId: string) { const { data: job, error: jobError } = await supabase.from("jobs").select("id, quote_id").eq("organization_id", organizationId).eq("id", jobId).maybeSingle(); if (jobError || !job?.quote_id) return false; const [{ data: quote, error: quoteError }, { data: payments, error: paymentError }] = await Promise.all([supabase.from("quotes").select("total, deposit_required").eq("organization_id", organizationId).eq("id", job.quote_id).maybeSingle(), supabase.from("payments").select("amount, payment_type, status").eq("organization_id", organizationId).eq("job_id", jobId)]); if (quoteError || paymentError || !quote) return false; const paid = paymentTotal(payments ?? []); const total = Number(quote.total); const deposit = Number(quote.deposit_required); const paymentStatus = paid <= 0 ? "deposit_pending" : paid >= total ? "paid" : deposit > 0 && paid >= deposit ? "deposit_paid" : "partially_paid"; const { error } = await supabase.from("jobs").update({ payment_status: paymentStatus, updated_at: new Date().toISOString() }).eq("organization_id", organizationId).eq("id", jobId); return !error; }

export async function createPaymentAction(_state: CrmActionState, formData: FormData): Promise<CrmActionState> { const jobId = value(formData, "job_id"); if (!jobId) return { error: "Job information is missing." }; const parsed = paymentValues(formData); if ("error" in parsed) return { error: parsed.error }; const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient(); const { data: job, error: jobError } = await supabase.from("jobs").select("id, customer_id, quote_id").eq("organization_id", organization.id).eq("id", jobId).maybeSingle(); if (jobError) return { error: "We could not check this job." }; if (!job?.quote_id) return { error: "Job or related quote not found." }; const { data: payment, error } = await supabase.from("payments").insert({ ...parsed.data, organization_id: organization.id, customer_id: job.customer_id, job_id: jobId, quote_id: job.quote_id }).select("id").single(); if (error || !payment) return { error: "We could not record this payment." }; if (!await recalculate(supabase, organization.id, jobId)) { await supabase.from("payments").delete().eq("organization_id", organization.id).eq("id", payment.id); return { error: "We could not finish updating the job balance." }; } redirect(`/jobs/${jobId}?payment=added`); }
export async function updatePaymentAction(_state: CrmActionState, formData: FormData): Promise<CrmActionState> { const paymentId = value(formData, "payment_id"); if (!paymentId) return { error: "Payment information is missing." }; const parsed = paymentValues(formData); if ("error" in parsed) return { error: parsed.error }; const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("payments").update({ ...parsed.data, updated_at: new Date().toISOString() }).eq("organization_id", organization.id).eq("id", paymentId).select("job_id").maybeSingle(); if (error) return { error: "We could not update this payment." }; if (!data?.job_id) return { error: "Payment not found." }; if (!await recalculate(supabase, organization.id, data.job_id)) return { error: "Payment saved, but the job balance could not be updated." }; redirect(`/jobs/${data.job_id}?payment=updated`); }
export async function deletePaymentAction(_state: CrmActionState, formData: FormData): Promise<CrmActionState> { const paymentId = value(formData, "payment_id"); if (!paymentId) return { error: "Payment information is missing." }; const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient(); const { data: payment, error: loadError } = await supabase.from("payments").select("id, job_id").eq("organization_id", organization.id).eq("id", paymentId).maybeSingle(); if (loadError) return { error: "We could not check this payment." }; if (!payment?.job_id) return { error: "Payment not found." }; const { error } = await supabase.from("payments").delete().eq("organization_id", organization.id).eq("id", paymentId); if (error) return { error: "We could not delete this payment." }; if (!await recalculate(supabase, organization.id, payment.job_id)) return { error: "Payment deleted, but the job balance could not be updated." }; redirect(`/jobs/${payment.job_id}?payment=deleted`); }
