"use server";

import { redirect } from "next/navigation";
import type { CrmActionState } from "@/app/actions/customers";
import { requireOrganization } from "@/lib/auth/current";
import { quoteStatuses } from "@/lib/quote-options";
import { createSupabaseServerClient } from "@/lib/supabase/server";

const value = (formData: FormData, name: string) => String(formData.get(name) ?? "").trim();
function logQuoteFailure(stage: string, error: unknown, context: Record<string, unknown> = {}) { console.error("[quotes] create/update failed", { stage, context, error }); }
type IncomingLine = { catalog_item_id?: string | null; description?: string; quantity?: number | string; unit?: string; unit_price?: number | string; multiplier?: number | string; customer_visible?: boolean; notes?: string | null };

function quoteValues(formData: FormData) {
  const customerId = value(formData, "customer_id"); const propertyId = value(formData, "property_id"); const siteVisitId = value(formData, "site_visit_id") || null; const packageId = value(formData, "package_id") || null; const status = value(formData, "status"); const quoteDate = value(formData, "quote_date"); const expirationDate = value(formData, "expiration_date") || null; const discount = Number(value(formData, "discount") || 0); const depositType = value(formData, "deposit_type"); const depositValue = Number(value(formData, "deposit_value") || 0);
  if (!customerId || !propertyId) return { error: "Choose a customer and property." } as const; if (!quoteStatuses.includes(status as typeof quoteStatuses[number])) return { error: "Choose a valid quote status." } as const; if (!/^\d{4}-\d{2}-\d{2}$/.test(quoteDate)) return { error: "Choose a valid quote date." } as const; if (expirationDate && !/^\d{4}-\d{2}-\d{2}$/.test(expirationDate)) return { error: "Choose a valid expiration date." } as const; if (!Number.isFinite(discount) || discount < 0) return { error: "Discount must be zero or greater." } as const; if (!['percentage', 'fixed'].includes(depositType) || !Number.isFinite(depositValue) || depositValue < 0) return { error: "Enter a valid deposit." } as const;
  let incoming: IncomingLine[]; try { incoming = JSON.parse(value(formData, "line_items") || "[]") as IncomingLine[]; } catch { return { error: "We could not read the quote line items." } as const; }
  if (!Array.isArray(incoming) || !incoming.length) return { error: "Add at least one quote line item." } as const;
  const lines = [] as Array<{ catalog_item_id: string | null; description: string; quantity: string; unit: string; unit_price: string; multiplier: string; line_total: string; customer_visible: boolean; notes: string | null }>;
  for (const item of incoming) { const description = String(item.description ?? "").trim(); const quantityValue = String(item.quantity ?? "").trim(); const unitPriceValue = String(item.unit_price ?? "").trim(); const multiplierValue = String(item.multiplier ?? "").trim(); const quantity = Number(quantityValue); const unitPrice = Number(unitPriceValue); const multiplier = Number(multiplierValue); const unit = String(item.unit ?? "").trim(); if (!description) return { error: "Every line item needs a description." } as const; if (!quantityValue || !unitPriceValue || !multiplierValue) return { error: `Complete quantity, price, and multiplier for ${description}.` } as const; if (!Number.isFinite(quantity) || quantity < 0 || !Number.isFinite(unitPrice) || unitPrice < 0 || !Number.isFinite(multiplier) || multiplier < 0) return { error: `Enter valid nonnegative pricing for ${description}.` } as const; if (!unit) return { error: `Choose a unit for ${description}.` } as const; lines.push({ catalog_item_id: item.catalog_item_id || null, description, quantity: String(quantity), unit, unit_price: String(unitPrice), multiplier: String(multiplier), line_total: String(quantity * unitPrice * multiplier), customer_visible: item.customer_visible !== false, notes: String(item.notes ?? "").trim() || null }); }
  const subtotal = lines.reduce((sum, item) => sum + Number(item.line_total), 0); const total = Math.max(0, subtotal - discount); const requestedDeposit = depositType === "percentage" ? total * depositValue / 100 : depositValue; const depositRequired = Math.min(total, requestedDeposit); const balanceDue = Math.max(0, total - depositRequired);
  return { data: { customer_id: customerId, property_id: propertyId, site_visit_id: siteVisitId, package_id: packageId, status, quote_date: quoteDate, expiration_date: expirationDate, subtotal: String(subtotal), discount: String(discount), total: String(total), deposit_type: depositType, deposit_value: String(depositValue), deposit_required: String(depositRequired), balance_due: String(balanceDue), customer_notes: value(formData, "customer_notes") || null, terms: value(formData, "terms") || null, internal_notes: value(formData, "internal_notes") || null }, lines } as const;
}

async function validateRelations(supabase: Awaited<ReturnType<typeof createSupabaseServerClient>>, organizationId: string, data: { customer_id: string; property_id: string; site_visit_id: string | null; package_id: string | null }, lines: Array<{ catalog_item_id: string | null }>) {
  const [customer, property, visit, packageResult] = await Promise.all([supabase.from("customers").select("id").eq("organization_id", organizationId).eq("id", data.customer_id).maybeSingle(), supabase.from("properties").select("id, customer_id").eq("organization_id", organizationId).eq("id", data.property_id).maybeSingle(), data.site_visit_id ? supabase.from("site_visits").select("id, customer_id, property_id").eq("organization_id", organizationId).eq("id", data.site_visit_id).maybeSingle() : Promise.resolve({ data: null, error: null }), data.package_id ? supabase.from("packages").select("id").eq("organization_id", organizationId).eq("id", data.package_id).maybeSingle() : Promise.resolve({ data: null, error: null })]);
  if (customer.error || property.error || visit.error || packageResult.error) return "We could not check the quote relationships."; if (!customer.data) return "Customer not found."; if (!property.data || property.data.customer_id !== data.customer_id) return "Choose a property belonging to this customer."; if (data.site_visit_id && (!visit.data || visit.data.customer_id !== data.customer_id || visit.data.property_id !== data.property_id)) return "Choose a site visit for this customer and property."; if (data.package_id && !packageResult.data) return "Package not found.";
  const catalogIds = [...new Set(lines.map((item) => item.catalog_item_id).filter((id): id is string => Boolean(id)))]; if (catalogIds.length) { const { data: catalog, error } = await supabase.from("catalog_items").select("id").eq("organization_id", organizationId).in("id", catalogIds); if (error) return "We could not check catalog items."; if ((catalog ?? []).length !== catalogIds.length) return "One or more catalog items could not be found."; } return null;
}

async function nextQuoteNumber(supabase: Awaited<ReturnType<typeof createSupabaseServerClient>>, organizationId: string) { const year = new Date().getFullYear(); for (let attempt = 0; attempt < 5; attempt += 1) { const suffix = `${Date.now()}`.slice(-6) + String(Math.floor(Math.random() * 10)); const number = `Q-${year}-${suffix}`; const { data } = await supabase.from("quotes").select("id").eq("organization_id", organizationId).eq("quote_number", number).maybeSingle(); if (!data) return number; } return `Q-${year}-${crypto.randomUUID().slice(0, 8).toUpperCase()}`; }
async function updateCustomerStatus(supabase: Awaited<ReturnType<typeof createSupabaseServerClient>>, organizationId: string, customerId: string, status: string) { if (status === "sent") await supabase.from("customers").update({ status: "quote_sent", updated_at: new Date().toISOString() }).eq("organization_id", organizationId).eq("id", customerId).in("status", ["lead", "contacted", "site_visit_scheduled", "measured"]); if (status === "approved") await supabase.from("customers").update({ status: "approved", updated_at: new Date().toISOString() }).eq("organization_id", organizationId).eq("id", customerId).in("status", ["lead", "contacted", "site_visit_scheduled", "measured", "quote_sent"]); }

export async function createQuoteAction(_state: CrmActionState, formData: FormData): Promise<CrmActionState> {
  const parsed = quoteValues(formData);
  if ("error" in parsed) { logQuoteFailure("validation", parsed.error, { customer_id: value(formData, "customer_id"), property_id: value(formData, "property_id"), package_id: value(formData, "package_id"), line_count: (() => { try { const lines = JSON.parse(value(formData, "line_items") || "[]"); return Array.isArray(lines) ? lines.length : 0; } catch { return 0; } })() }); return { error: parsed.error }; }
  const { organization } = await requireOrganization();
  const supabase = await createSupabaseServerClient();
  const context = { organization_id: organization.id, customer_id: parsed.data.customer_id, property_id: parsed.data.property_id, site_visit_id: parsed.data.site_visit_id, package_id: parsed.data.package_id, line_count: parsed.lines.length, subtotal: parsed.data.subtotal, total: parsed.data.total };
  const relationshipError = await validateRelations(supabase, organization.id, parsed.data, parsed.lines);
  if (relationshipError) { logQuoteFailure("relationship-validation", relationshipError, context); return { error: relationshipError }; }
  const quoteNumber = await nextQuoteNumber(supabase, organization.id);
  const { data: quote, error } = await supabase.from("quotes").insert({ ...parsed.data, organization_id: organization.id, quote_number: quoteNumber }).select("id").single();
  if (error || !quote) { logQuoteFailure("quote-insert", error ?? "No quote returned", { ...context, quote_number: quoteNumber }); return { error: error?.code === "42501" ? "Your account does not have permission to create quotes. Apply the quote RLS policy migration." : "We could not create this quote. Please try again." }; }
  const { error: lineError } = await supabase.from("quote_line_items").insert(parsed.lines.map((item) => ({ ...item, organization_id: organization.id, quote_id: quote.id })));
  if (lineError) { logQuoteFailure("line-item-insert", lineError, { ...context, quote_id: quote.id }); const { error: rollbackError } = await supabase.from("quotes").delete().eq("organization_id", organization.id).eq("id", quote.id); if (rollbackError) logQuoteFailure("quote-rollback", rollbackError, { quote_id: quote.id, organization_id: organization.id }); return { error: lineError.code === "42501" ? "Your account does not have permission to save quote line items. Apply the quote RLS policy migration." : "We could not save the quote line items. Please try again." }; }
  await updateCustomerStatus(supabase, organization.id, parsed.data.customer_id, parsed.data.status);
  console.info("[quotes] created", { quote_id: quote.id, quote_number: quoteNumber, organization_id: organization.id, line_count: parsed.lines.length });
  redirect(`/quotes/${quote.id}?created=1`);
}
export async function updateQuoteAction(_state: CrmActionState, formData: FormData): Promise<CrmActionState> { const quoteId = value(formData, "quote_id"); if (!quoteId) return { error: "Quote information is missing." }; const parsed = quoteValues(formData); if ("error" in parsed) return { error: parsed.error }; const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient(); const relationshipError = await validateRelations(supabase, organization.id, parsed.data, parsed.lines); if (relationshipError) return { error: relationshipError }; const { data, error } = await supabase.from("quotes").update({ ...parsed.data, updated_at: new Date().toISOString() }).eq("organization_id", organization.id).eq("id", quoteId).select("id").maybeSingle(); if (error) return { error: "We could not update this quote." }; if (!data) return { error: "Quote not found." }; const { error: deleteError } = await supabase.from("quote_line_items").delete().eq("organization_id", organization.id).eq("quote_id", quoteId); if (deleteError) return { error: "We could not update quote line items." }; const { error: lineError } = await supabase.from("quote_line_items").insert(parsed.lines.map((item) => ({ ...item, organization_id: organization.id, quote_id: quoteId }))); if (lineError) return { error: "The quote was updated, but its line items could not be saved. Please try again." }; await updateCustomerStatus(supabase, organization.id, parsed.data.customer_id, parsed.data.status); redirect(`/quotes/${quoteId}?updated=1`); }
export async function updateQuoteStatusAction(_state: CrmActionState, formData: FormData): Promise<CrmActionState> { const quoteId = value(formData, "quote_id"); const status = value(formData, "status"); if (!quoteId || !quoteStatuses.includes(status as typeof quoteStatuses[number])) return { error: "Choose a valid quote status." }; const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("quotes").update({ status, updated_at: new Date().toISOString() }).eq("organization_id", organization.id).eq("id", quoteId).select("customer_id").maybeSingle(); if (error) return { error: "We could not change this quote’s status." }; if (!data) return { error: "Quote not found." }; await updateCustomerStatus(supabase, organization.id, data.customer_id, status); redirect(`/quotes/${quoteId}?status=${status}`); }
export async function deleteDraftQuoteAction(_state: CrmActionState, formData: FormData): Promise<CrmActionState> { const quoteId = value(formData, "quote_id"); if (!quoteId) return { error: "Quote information is missing." }; const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("quotes").delete().eq("organization_id", organization.id).eq("id", quoteId).eq("status", "draft").select("id").maybeSingle(); if (error) return { error: "We could not delete this draft quote." }; if (!data) return { error: "Only draft quotes can be deleted." }; redirect("/quotes?deleted=1"); }
