"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requireOrganization } from "@/lib/auth/current";
import { createSupabaseServerClient } from "@/lib/supabase/server";
export type ScheduleActionState = { error?: string };
const value = (data: FormData, key: string) => String(data.get(key) ?? "").trim();
const types = new Set(["site_visit", "install", "takedown", "service_call", "follow_up", "maintenance", "other"]); const statuses = new Set(["scheduled", "completed", "rescheduled", "canceled"]);
async function parse(formData: FormData, organizationId: string) { const event_type = value(formData, "event_type"), event_date = value(formData, "event_date"), status = value(formData, "status"), customer_id = value(formData, "customer_id") || null, property_id = value(formData, "property_id") || null, job_id = value(formData, "job_id") || null, start_time = value(formData, "start_time") || null, end_time = value(formData, "end_time") || null; if (!types.has(event_type)) return { error: "Choose a valid event type." } as const; if (!/^\d{4}-\d{2}-\d{2}$/.test(event_date)) return { error: "Choose an event date." } as const; if (!statuses.has(status)) return { error: "Choose a valid event status." } as const; if (start_time && end_time && end_time < start_time) return { error: "End time cannot be before start time." } as const; const supabase = await createSupabaseServerClient(); if (customer_id) { const { data } = await supabase.from("customers").select("id").eq("organization_id", organizationId).eq("id", customer_id).maybeSingle(); if (!data) return { error: "Customer not found." } as const; } if (property_id) { const { data } = await supabase.from("properties").select("id, customer_id").eq("organization_id", organizationId).eq("id", property_id).maybeSingle(); if (!data || (customer_id && data.customer_id !== customer_id)) return { error: "Choose a property belonging to this customer." } as const; } if (job_id) { const { data } = await supabase.from("jobs").select("id, customer_id, property_id").eq("organization_id", organizationId).eq("id", job_id).maybeSingle(); if (!data || (customer_id && data.customer_id !== customer_id) || (property_id && data.property_id !== property_id)) return { error: "Choose a job connected to this customer and property." } as const; } return { data: { organization_id: organizationId, event_type, event_date, start_time, end_time, time_window: value(formData, "time_window") || null, status, customer_id, property_id, job_id, assigned_user_id: value(formData, "assigned_user_id") || null, notes: value(formData, "notes") || null, updated_at: new Date().toISOString() } } as const; }
export async function createScheduleEventAction(_state: ScheduleActionState, formData: FormData): Promise<ScheduleActionState> { const { organization } = await requireOrganization(); const parsed = await parse(formData, organization.id); if ("error" in parsed) return { error: parsed.error }; const supabase = await createSupabaseServerClient(); const { error } = await supabase.from("schedule_events").insert(parsed.data); if (error) return { error: "We could not create this schedule event." }; redirect("/schedule?created=1"); }
export async function updateScheduleEventAction(_state: ScheduleActionState, formData: FormData): Promise<ScheduleActionState> { const id = value(formData, "event_id"); if (!id) return { error: "Event information is missing." }; const { organization } = await requireOrganization(); const parsed = await parse(formData, organization.id); if ("error" in parsed) return { error: parsed.error }; const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("schedule_events").update(parsed.data).eq("organization_id", organization.id).eq("id", id).select("id").maybeSingle(); if (error) return { error: "We could not update this schedule event." }; if (!data) return { error: "Schedule event not found." }; redirect("/schedule?updated=1"); }
export async function completeScheduleEventAction(formData: FormData) { const id = value(formData, "event_id"); const { organization } = await requireOrganization(); const supabase = await createSupabaseServerClient(); const { data } = await supabase.from("schedule_events").update({ status: "completed", updated_at: new Date().toISOString() }).eq("organization_id", organization.id).eq("id", id).select("job_id, event_type").maybeSingle(); if (data?.job_id && data.event_type === "install") await supabase.from("jobs").update({ status: "installed", updated_at: new Date().toISOString() }).eq("organization_id", organization.id).eq("id", data.job_id).neq("status", "canceled"); if (data?.job_id && data.event_type === "takedown") await supabase.from("jobs").update({ status: "takedown_complete", updated_at: new Date().toISOString() }).eq("organization_id", organization.id).eq("id", data.job_id).neq("status", "canceled"); revalidatePath("/schedule"); }
