import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, MapPin, Pencil, Ruler } from "lucide-react";
import { DeleteMeasurementForm } from "@/components/measurements/delete-measurement-form";
import { FileSection } from "@/components/files/file-section";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { LinkButton } from "@/components/ui/link-button";
import { PageHeader } from "@/components/ui/page-header";
import { requireOrganization } from "@/lib/auth/current";
import { customerName, formatDate, formatVisitDate, propertyAddress } from "@/lib/format";
import { getMeasurement } from "@/lib/measurements";

function Detail({ label, value }: { label: string; value?: string | null }) { return <div className="rounded-xl bg-slate-50 p-4"><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-sm font-semibold leading-6 text-slate-900">{value || "Not provided"}</dd></div>; }

export default async function MeasurementDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ updated?: string }> }) {
  const { organization } = await requireOrganization(); const { id } = await params; const notice = await searchParams;
  const measurement = await getMeasurement(organization.id, id); if (!measurement) notFound(); const visit = measurement.site_visit;
  const quantity = Number(measurement.quantity).toLocaleString("en-US", { maximumFractionDigits: 2 });
  return <div className="space-y-7"><PageHeader title={measurement.zone_name} description={`${measurement.measurement_type} · ${quantity} ${measurement.unit}`} actions={<div className="flex flex-wrap gap-2"><LinkButton href={`/site-visits/${visit.id}`} variant="secondary"><ArrowLeft className="mr-2 size-4" />Back to Site Visit</LinkButton><LinkButton href={`/measurements/${id}/edit`}><Pencil className="mr-2 size-4" />Edit</LinkButton></div>} />{notice.updated === "1" ? <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">Measurement changes saved.</div> : null}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]"><Card><CardHeader className="flex flex-row items-center justify-between"><h2 className="font-bold text-slate-950">Measurement Details</h2><Badge variant={measurement.included_in_quote ? "success" : "neutral"}>{measurement.included_in_quote ? "Included in quote" : "Excluded from quote"}</Badge></CardHeader><CardContent className="space-y-4"><dl className="grid gap-4 sm:grid-cols-2"><Detail label="Measurement type" value={measurement.measurement_type} /><Detail label="Quantity" value={`${quantity} ${measurement.unit}`} /><Detail label="Height level" value={measurement.height_level} /><Detail label="Difficulty" value={`${measurement.difficulty || "Normal"} · ${Number(measurement.difficulty_multiplier).toLocaleString("en-US", { maximumFractionDigits: 2 })}×`} /><Detail label="Catalog item" value={measurement.catalog_item?.name} /><Detail label="Pricing method" value={measurement.catalog_item?.pricing_method.replaceAll("_", " ")} /><div className="sm:col-span-2"><Detail label="Notes" value={measurement.notes} /></div></dl><div className="grid gap-1 border-t border-slate-100 pt-4 text-xs text-slate-500 sm:grid-cols-2"><p>Created {formatDate(measurement.created_at)}</p><p className="sm:text-right">Updated {formatDate(measurement.updated_at)}</p></div></CardContent></Card>
      <Card><CardHeader><h2 className="font-bold text-slate-950">Connected Records</h2></CardHeader><CardContent className="space-y-4"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Customer</p><Link href={`/customers/${visit.customer.id}`} className="mt-1 block text-sm font-semibold text-amber-800 hover:text-amber-700">{customerName(visit.customer.first_name, visit.customer.last_name)}</Link></div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Property</p><Link href={`/properties/${visit.property.id}`} className="mt-1 block text-sm font-semibold leading-5 text-amber-800 hover:text-amber-700">{visit.property.property_name || propertyAddress(visit.property)}</Link></div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Site visit</p><Link href={`/site-visits/${visit.id}`} className="mt-1 block text-sm font-semibold text-amber-800 hover:text-amber-700">{formatVisitDate(visit.visit_date)}</Link></div><div className="space-y-3 border-t border-slate-100 pt-4"><LinkButton href={`/measurements/${id}/edit`} className="w-full"><Pencil className="mr-2 size-4" />Edit Measurement</LinkButton><LinkButton href={`/site-visits/${visit.id}`} variant="secondary" className="w-full"><Ruler className="mr-2 size-4" />Back to Measurements</LinkButton><DeleteMeasurementForm measurementId={id} zoneName={measurement.zone_name} /></div></CardContent></Card></div>
    <FileSection organizationId={organization.id} relatedType="measurements" relatedId={id} photoTypes={["Roofline", "Garland area", "Walkway", "Tree/Bush", "Wreath location", "Outlet", "Safety issue", "Other"]} emptyText="No measurement photos yet." helperText="Add photos after saving this measurement." />
  </div>;
}
