import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Camera, FileText, MailQuestion, MapPin, Pencil, Plus, Ruler } from "lucide-react";
import { MeasurementCard } from "@/components/measurements/measurement-card";
import { FileSection } from "@/components/files/file-section";
import { RelatedQuotes } from "@/components/quotes/related-quotes";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { LinkButton } from "@/components/ui/link-button";
import { PageHeader } from "@/components/ui/page-header";
import { requireOrganization } from "@/lib/auth/current";
import { customerName, formatDate, formatVisitDate, propertyAddress } from "@/lib/format";
import { getSiteVisit } from "@/lib/site-visits";
import { getMeasurementsForSiteVisit, summarizeMeasurements } from "@/lib/measurements";
import { getQuotesForSiteVisit } from "@/lib/quotes";

function Detail({ label, value }: { label: string; value?: string | null }) {
  return <div className="rounded-xl bg-slate-50 p-4"><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-sm font-semibold leading-6 text-slate-900">{value || "Not provided"}</dd></div>;
}

export default async function SiteVisitDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ created?: string; updated?: string; measurement?: string }> }) {
  const { organization } = await requireOrganization(); const { id } = await params; const notice = await searchParams;
  const [visit, measurements, quotes] = await Promise.all([getSiteVisit(organization.id, id), getMeasurementsForSiteVisit(organization.id, id), getQuotesForSiteVisit(organization.id, id)]); if (!visit) notFound();
  const name = customerName(visit.customer.first_name, visit.customer.last_name);
  const summary = summarizeMeasurements(measurements);
  return <div className="space-y-7"><PageHeader title="Site Visit" description={`${formatVisitDate(visit.visit_date)} · ${name}`} actions={<div className="flex flex-wrap gap-2"><LinkButton href="/site-visits" variant="secondary"><ArrowLeft className="mr-2 size-4" />Site Visits</LinkButton><LinkButton href={`/site-visits/${id}/edit`}><Pencil className="mr-2 size-4" />Edit Visit</LinkButton></div>} />
    {notice.created === "1" ? <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">Site visit scheduled successfully.</div> : null}{notice.updated === "1" ? <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">Site visit changes saved.</div> : null}{notice.measurement === "added" ? <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">Measurement added.</div> : null}{notice.measurement === "deleted" ? <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">Measurement deleted.</div> : null}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]"><Card><CardHeader><h2 className="font-bold text-slate-950">Visit Details</h2></CardHeader><CardContent className="space-y-4"><dl className="grid gap-4 sm:grid-cols-2"><Detail label="Visit date" value={formatVisitDate(visit.visit_date)} /><div className="rounded-xl bg-slate-50 p-4"><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">Customer</dt><dd className="mt-1 text-sm font-semibold"><Link href={`/customers/${visit.customer.id}`} className="text-amber-800 hover:text-amber-700">{name}</Link></dd></div><div className="rounded-xl bg-slate-50 p-4 sm:col-span-2"><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">Property</dt><dd className="mt-1 text-sm font-semibold"><Link href={`/properties/${visit.property.id}`} className="text-amber-800 hover:text-amber-700">{visit.property.property_name || propertyAddress(visit.property)}</Link></dd></div><Detail label="Budget discussed" value={visit.budget_discussed} /><Detail label="Preferred style" value={visit.preferred_style} /><div className="rounded-xl bg-slate-50 p-4"><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">Preferred colors</dt><dd className="mt-2 flex flex-wrap gap-2">{visit.preferred_colors.length ? visit.preferred_colors.map((color) => <Badge key={color}>{color}</Badge>) : <span className="text-sm font-semibold text-slate-900">Not selected</span>}</dd></div><Detail label="Customer present" value={visit.customer_present ? "Yes" : "No"} /><div className="sm:col-span-2"><Detail label="Visit notes" value={visit.notes} /></div></dl><div className="grid gap-1 border-t border-slate-100 pt-4 text-xs text-slate-500 sm:grid-cols-2"><p>Created {formatDate(visit.created_at)}</p><p className="sm:text-right">Updated {formatDate(visit.updated_at)}</p></div></CardContent></Card>
      <Card><CardHeader><h2 className="font-bold text-slate-950">Visit Actions</h2></CardHeader><CardContent className="space-y-3"><LinkButton href={`/site-visits/${id}/measurements/new`} className="w-full"><Plus className="mr-2 size-4" />Add Measurement</LinkButton><LinkButton href={`/site-visits/${id}/edit`} variant="secondary" className="w-full"><Pencil className="mr-2 size-4" />Edit Site Visit</LinkButton><LinkButton href={`/properties/${visit.property.id}`} variant="ghost" className="w-full"><MapPin className="mr-2 size-4" />Back to Property</LinkButton><LinkButton href={`/customers/${visit.customer.id}`} variant="ghost" className="w-full"><ArrowLeft className="mr-2 size-4" />Back to Customer</LinkButton></CardContent></Card></div>
    <section id="measurements" aria-labelledby="measurements-title" className="scroll-mt-24"><div className="mb-3 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 id="measurements-title" className="text-xl font-bold text-slate-950">Measurements</h2><p className="mt-1 text-sm text-slate-500">Measured zones ready for future quoting.</p></div><LinkButton href={`/site-visits/${id}/measurements/new`} size="sm"><Plus className="mr-2 size-4" />Add Measurement</LinkButton></div>
      <div className="mb-4 grid gap-3 grid-cols-2 sm:grid-cols-4 xl:grid-cols-7">{[{ label: "Total", value: summary.count }, { label: "Roofline ft", value: summary.rooflineFeet }, { label: "Garland ft", value: summary.garlandFeet }, { label: "Walkway ft", value: summary.walkwayFeet }, { label: "Wreaths", value: summary.wreathCount }, { label: "Trees", value: summary.treeCount }, { label: "Bushes", value: summary.bushCount }].map((item) => <Card key={item.label} className="shadow-none"><CardContent className="p-3"><p className="text-xs font-semibold text-slate-500">{item.label}</p><p className="mt-1 text-xl font-extrabold text-slate-950">{item.value}</p></CardContent></Card>)}</div>
      {measurements.length ? <div className="grid gap-4 lg:grid-cols-2">{measurements.map((measurement) => <MeasurementCard key={measurement.id} measurement={measurement} allowDelete />)}</div> : <EmptyState compact icon={<Ruler className="size-5" />} title="No measurements yet" description="Add the first roofline, garland, walkway, wreath, tree, or other property zone." actionLabel="Add Measurement" actionHref={`/site-visits/${id}/measurements/new`} />}
    </section>
    <RelatedQuotes quotes={quotes} createHref={`/site-visits/${id}/quotes/new`} />
    <section aria-labelledby="next-steps-title"><h2 id="next-steps-title" className="mb-3 text-xl font-bold text-slate-950">Coming Later</h2><div className="grid gap-3 sm:grid-cols-3">{[{ id: "photos", label: "Photos", detail: "Property photos will live here.", icon: Camera }, { id: "quote", label: "Quote", detail: "Build a quote after measurements.", icon: FileText }, { id: "follow-up", label: "Follow-up", detail: "Customer follow-up is coming later.", icon: MailQuestion }].map(({ id: sectionId, label, detail, icon: Icon }) => <Card id={sectionId} key={label} className="scroll-mt-24 shadow-none"><CardContent className="flex items-start gap-3 p-4"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-slate-600"><Icon className="size-4" /></span><div><p className="text-sm font-bold text-slate-900">{label}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></div></CardContent></Card>)}</div></section>
    <FileSection organizationId={organization.id} relatedType="site-visits" relatedId={id} photoTypes={["Front of house", "Roofline", "Outlet", "Walkway", "Tree/Bush", "Safety issue", "Design idea", "Other"]} emptyText="No site visit photos yet. Add photos from the visit to support measurements and quoting." />
  </div>;
}
