"use client";

import { useActionState, useEffect, useState } from "react";
import { useFormStatus } from "react-dom";
import { Check, Clipboard, Printer, Send, X } from "lucide-react";
import { approveProposalAction, declineProposalAction, generateProposalLinkAction, markProposalSentAction } from "@/app/actions/proposals";
import { FormMessage } from "@/components/auth/form-fields";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

function PendingButton({ label, pendingLabel, icon: Icon, variant = "secondary" }: { label: string; pendingLabel: string; icon: typeof Send; variant?: "primary" | "secondary" | "danger" }) { const { pending } = useFormStatus(); return <Button type="submit" variant={variant} disabled={pending}><Icon className="mr-2 size-4" />{pending ? pendingLabel : label}</Button>; }
export function PrintProposalButton() { return <Button type="button" variant="secondary" onClick={() => window.print()}><Printer className="mr-2 size-4" />Print / Save PDF</Button>; }
export function CopyProposalLink({ token }: { token: string }) { const path = `/proposal/${token}`; const [link, setLink] = useState(path); const [message, setMessage] = useState(""); useEffect(() => setLink(`${window.location.origin}${path}`), [path]); const copy = async () => { try { await navigator.clipboard.writeText(link); setMessage("Proposal link copied."); } catch { setMessage("Copy the link from the field below."); } }; return <div className="space-y-2"><div className="flex flex-col gap-2 sm:flex-row"><Input readOnly value={link} aria-label="Proposal share link" /><Button type="button" variant="secondary" onClick={copy}><Clipboard className="mr-2 size-4" />Copy Link</Button></div>{message ? <p role="status" className="text-xs text-slate-600">{message}</p> : null}</div>; }
export function GenerateProposalLinkForm({ quoteId }: { quoteId: string }) { const [state, action] = useActionState(generateProposalLinkAction, {}); return <form action={action} className="space-y-2"><input type="hidden" name="quote_id" value={quoteId} /><FormMessage error={state.error} /><PendingButton label="Generate Proposal Link" pendingLabel="Generating…" icon={Clipboard} /></form>; }
export function MarkProposalSentForm({ quoteId }: { quoteId: string }) { const [state, action] = useActionState(markProposalSentAction, {}); return <form action={action} className="space-y-2"><input type="hidden" name="quote_id" value={quoteId} /><FormMessage error={state.error} /><PendingButton label="Mark Proposal Sent" pendingLabel="Updating…" icon={Send} /></form>; }
export function ProposalDecisionForms({ token, defaultName, defaultEmail }: { token: string; defaultName: string; defaultEmail?: string | null }) { const [approveState, approveAction] = useActionState(approveProposalAction, {}); const [declineState, declineAction] = useActionState(declineProposalAction, {}); return <div className="grid gap-5 lg:grid-cols-2"><form action={approveAction} className="space-y-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><input type="hidden" name="proposal_token" value={token} /><div><h3 className="text-lg font-bold text-emerald-950">Approve Proposal</h3><p className="mt-1 text-sm text-emerald-800">Confirm your name and acceptance below.</p></div><FormMessage error={approveState.error} /><label className="block text-sm font-semibold text-slate-800">Customer name<Input className="mt-2" name="customer_name" required defaultValue={defaultName} /></label><label className="block text-sm font-semibold text-slate-800">Customer email <span className="font-normal text-slate-500">(optional)</span><Input className="mt-2" name="customer_email" type="email" defaultValue={defaultEmail ?? ""} /></label><label className="flex items-start gap-3 rounded-xl bg-white p-3 text-sm leading-6 text-slate-700"><input name="approval_confirmed" type="checkbox" required className="mt-1 size-4 accent-emerald-700" />I approve this proposal and understand the deposit is required to reserve my installation date.</label><PendingButton label="Approve Proposal" pendingLabel="Approving…" icon={Check} variant="primary" /></form><form action={declineAction} className="space-y-4 rounded-2xl border border-red-200 bg-red-50 p-5"><input type="hidden" name="proposal_token" value={token} /><div><h3 className="text-lg font-bold text-red-950">Decline Proposal</h3><p className="mt-1 text-sm text-red-800">You may share a reason to help the installer follow up.</p></div><FormMessage error={declineState.error} /><label className="block text-sm font-semibold text-slate-800">Reason <span className="font-normal text-slate-500">(optional)</span><Textarea className="mt-2 bg-white" name="decline_reason" placeholder="Let us know what changed." /></label><PendingButton label="Decline Proposal" pendingLabel="Declining…" icon={X} variant="danger" /></form></div>; }
