import { Eye, FileText, Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { LinkButton } from "@/components/ui/link-button";
import { propertyAddress } from "@/lib/format";
import type { QuoteListRecord } from "@/lib/quotes";
const money = (value: string) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value));
export function RelatedQuotes({ quotes, createHref, showProperty = false }: { quotes: QuoteListRecord[]; createHref: string; showProperty?: boolean }) { return <section aria-labelledby="related-quotes-title"><div className="mb-3 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 id="related-quotes-title" className="text-xl font-bold text-slate-950">Quotes</h2><p className="mt-1 text-sm text-slate-500">Priced offers connected to this record.</p></div><LinkButton href={createHref} size="sm"><Plus className="mr-2 size-4" />Create Quote</LinkButton></div>{quotes.length ? <Card className="overflow-hidden"><div className="divide-y divide-slate-100">{quotes.map((quote) => <div key={quote.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><p className="font-bold text-slate-950">{quote.quote_number || `Quote ${quote.id.slice(0, 8).toUpperCase()}`}</p><Badge variant={quote.status === "approved" ? "success" : "neutral"}>{quote.status}</Badge></div><p className="mt-1 text-sm text-slate-600">{money(quote.total)} · {quote.quote_date}{quote.expiration_date ? ` · Expires ${quote.expiration_date}` : ""}</p>{showProperty ? <p className="mt-1 text-xs text-slate-500">{quote.property.property_name || propertyAddress(quote.property)}</p> : null}</div><div className="flex flex-wrap gap-2"><LinkButton href={`/quotes/${quote.id}/proposal`} size="sm" variant="secondary"><Eye className="mr-1.5 size-3.5" />View Proposal</LinkButton><LinkButton href={`/quotes/${quote.id}`} size="sm" variant="ghost">View Quote</LinkButton></div></div>)}</div></Card> : <EmptyState compact icon={<FileText className="size-5" />} title="No quotes yet" description="Create the first quote when pricing is ready." actionLabel="Create Quote" actionHref={createHref} />}</section>; }
