import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { LinkButton } from "@/components/ui/link-button";
import { optionLabel, paymentRecordStatuses, paymentTotal, paymentTypes } from "@/lib/payment-options";
import type { JobListRecord } from "@/lib/jobs";
import type { Payment } from "@/types/database";
const money = (value: number | string) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value));
export function CustomerPayments({ payments, jobs }: { payments: Payment[]; jobs: JobListRecord[] }) { const totalQuoted = jobs.reduce((sum, job) => sum + Number(job.quote?.total ?? 0), 0); const totalPaid = paymentTotal(payments); const openBalance = Math.max(0, totalQuoted - totalPaid); return <section aria-labelledby="customer-payments-title"><div className="mb-3"><h2 id="customer-payments-title" className="text-xl font-bold">Payments</h2><p className="mt-1 text-sm text-slate-500">Recent manual payments and open customer balance.</p></div><div className="mb-4 grid grid-cols-3 gap-3">{[["Total Quoted", totalQuoted], ["Total Paid", totalPaid], ["Open Balance", openBalance]].map(([label, amount]) => <Card key={String(label)} className="shadow-none"><CardContent className="p-3"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 text-lg font-extrabold">{money(amount)}</p></CardContent></Card>)}</div>{payments.length ? <Card className="overflow-hidden"><div className="divide-y">{payments.map((payment) => { const job = jobs.find((item) => item.id === payment.job_id); return <div key={payment.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{optionLabel(paymentTypes, payment.payment_type)} · {money(payment.amount)}</p><Badge variant={payment.status === "paid" ? "success" : "neutral"}>{optionLabel(paymentRecordStatuses, payment.status)}</Badge></div><p className="mt-1 text-xs text-slate-500">{payment.payment_date?.slice(0, 10) || "No date"}{job?.job_number ? ` · ${job.job_number}` : ""}</p></div>{payment.job_id ? <LinkButton href={`/jobs/${payment.job_id}`} size="sm" variant="secondary">View Job</LinkButton> : null}</div>; })}</div></Card> : <EmptyState compact title="No payments yet" description="Payments recorded from jobs will appear here." />}</section>; }
