import { ArrowLeft, Gift, Pencil, Plus } from "lucide-react";
import { notFound } from "next/navigation";
import { DeletePackageForm, PackageStatusForm, RemovePackageItemForm } from "@/components/packages/package-actions";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { LinkButton } from "@/components/ui/link-button";
import { PageHeader } from "@/components/ui/page-header";
import { requireOrganization } from "@/lib/auth/current";
import { formatDate } from "@/lib/format";
import { getPackage, type PackageItemRecord } from "@/lib/packages";

const money = (value: string | number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(Number(value));
function Summary({ label, value }: { label: string; value: string | number }) { return <Card className="shadow-none"><CardContent className="p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-xl font-extrabold text-slate-950">{value}</p></CardContent></Card>; }
function ItemSection({ packageId, title, description, items, type }: { packageId: string; title: string; description: string; items: PackageItemRecord[]; type: "included" | "addon" }) { return <section className="space-y-3"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-bold text-slate-950">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div><LinkButton href={`/packages/${packageId}/items/new?type=${type}`}><Plus className="mr-2 size-4" />{type === "included" ? "Add Item" : "Add Upgrade"}</LinkButton></div>{items.length ? <Card className="overflow-hidden"><div className="divide-y divide-slate-100">{items.map((item) => <div key={item.id} className="grid gap-4 p-4 lg:grid-cols-[minmax(0,1.5fr)_100px_110px_140px_minmax(180px,1fr)_auto] lg:items-center"><div><p className="font-bold text-slate-950">{item.catalog_item.name}</p><p className="mt-1 text-xs text-slate-500">{item.catalog_item.category}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Quantity</p><p className="mt-1 text-sm font-semibold">{Number(item.quantity).toLocaleString()} {item.unit}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Catalog Price</p><p className="mt-1 text-sm">{money(item.catalog_item.unit_price)}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Price Override</p><p className="mt-1 text-sm">{item.price_override === null ? "Use catalog price" : money(item.price_override)}</p></div><p className="text-sm text-slate-600">{item.notes || "No notes"}</p><div className="flex flex-wrap gap-2 lg:justify-end"><LinkButton href={`/packages/${packageId}/items/${item.id}/edit`} size="sm" variant="ghost"><Pencil className="mr-1.5 size-3.5" />Edit</LinkButton><RemovePackageItemForm packageId={packageId} itemId={item.id} /></div></div>)}</div></Card> : <EmptyState compact title={type === "included" ? "No included items yet" : "No optional add-ons yet"} description={type === "included" ? "Add the products and services covered by this package’s base price." : "Add upgrades customers can choose later during quoting."} actionLabel={type === "included" ? "Add Item" : "Add Upgrade"} actionHref={`/packages/${packageId}/items/new?type=${type}`} />}</section>; }

export default async function PackageDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ created?: string; updated?: string; status?: string; item?: string }> }) { const { organization } = await requireOrganization(); const { id } = await params; const notice = await searchParams; const packageRecord = await getPackage(organization.id, id); if (!packageRecord) notFound(); const included = packageRecord.items.filter((item) => item.included); const addons = packageRecord.items.filter((item) => item.optional_addon); const budget = packageRecord.recommended_budget_min || packageRecord.recommended_budget_max ? `${packageRecord.recommended_budget_min ? money(packageRecord.recommended_budget_min) : "Any"} – ${packageRecord.recommended_budget_max ? money(packageRecord.recommended_budget_max) : "Any"}` : "Not set"; const message = notice.created ? "Package created." : notice.updated ? "Package updated." : notice.status === "active" ? "Package reactivated." : notice.status === "inactive" ? "Package deactivated." : notice.item === "added" ? "Package item added." : notice.item === "updated" ? "Package item updated." : notice.item === "removed" ? "Package item removed. The catalog item was not deleted." : null;
  return <div className="space-y-7"><div><LinkButton href="/packages" variant="ghost" size="sm"><ArrowLeft className="mr-2 size-4" />Back to Packages</LinkButton></div><PageHeader title={packageRecord.name} description={packageRecord.description || "A reusable holiday lighting sales package."} actions={<div className="flex flex-wrap gap-2"><LinkButton href={`/packages/${id}/edit`} variant="secondary"><Pencil className="mr-2 size-4" />Edit Package</LinkButton><PackageStatusForm packageId={id} active={packageRecord.active} /></div>} />{message ? <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{message}</div> : null}<div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Summary label="Base Price" value={money(packageRecord.base_price)} /><Summary label="Included Items" value={packageRecord.includedCount} /><Summary label="Optional Add-ons" value={packageRecord.addonCount} /><Summary label="Included Retail Value" value={money(packageRecord.estimatedRetailValue)} /><Summary label="Recommended Budget" value={budget} /></div><Card><CardContent className="grid gap-5 p-5 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs font-bold uppercase text-slate-500">Status</p><Badge className="mt-2" variant={packageRecord.active ? "success" : "neutral"}>{packageRecord.active ? "Active" : "Inactive"}</Badge></div><div><p className="text-xs font-bold uppercase text-slate-500">Display Order</p><p className="mt-2 font-semibold">{packageRecord.display_order}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Created</p><p className="mt-2 text-sm">{formatDate(packageRecord.created_at)}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Updated</p><p className="mt-2 text-sm">{formatDate(packageRecord.updated_at)}</p></div></CardContent></Card><ItemSection packageId={id} title="Included Items" description="Products and services covered by the package base price." items={included} type="included" /><ItemSection packageId={id} title="Optional Add-ons" description="Upgrades available when building a customer quote later." items={addons} type="addon" /><Card><CardHeader><h2 className="font-bold text-slate-950">Package Actions</h2></CardHeader><CardContent><p className="mb-4 text-sm text-slate-500">Packages used by quotes cannot be deleted. Deactivate them to preserve history.</p><DeletePackageForm packageId={id} name={packageRecord.name} /></CardContent></Card></div>;
}
