import "server-only";

import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { Customer, Job, Property, Quote, QuoteLineItem } from "@/types/database";

type JobCustomer = Pick<Customer, "id" | "first_name" | "last_name">;
type JobProperty = Pick<Property, "id" | "property_name" | "address_line_1" | "address_line_2" | "city" | "state" | "zip">;
type JobQuote = Pick<Quote, "id" | "quote_number" | "total" | "deposit_required" | "balance_due" | "site_visit_id">;
export interface JobListRecord extends Job { customer: JobCustomer; property: JobProperty; quote: JobQuote | null; totalPaid?: number; remainingBalance?: number; }
export interface JobRecord extends Omit<JobListRecord, "quote"> { quote: JobQuote; line_items: QuoteLineItem[]; }

async function attach(organizationId: string, jobs: Job[]): Promise<JobListRecord[]> { if (!jobs.length) return []; const supabase = await createSupabaseServerClient(); const customerIds = [...new Set(jobs.map((item) => item.customer_id))]; const propertyIds = [...new Set(jobs.map((item) => item.property_id))]; const quoteIds = [...new Set(jobs.map((item) => item.quote_id).filter((id): id is string => Boolean(id)))]; const [customers, properties, quotes] = await Promise.all([supabase.from("customers").select("id, first_name, last_name").eq("organization_id", organizationId).in("id", customerIds), supabase.from("properties").select("id, property_name, address_line_1, address_line_2, city, state, zip").eq("organization_id", organizationId).in("id", propertyIds), quoteIds.length ? supabase.from("quotes").select("id, quote_number, total, deposit_required, balance_due, site_visit_id").eq("organization_id", organizationId).in("id", quoteIds) : Promise.resolve({ data: [], error: null })]); if (customers.error || properties.error || quotes.error) throw new Error("We could not load job details."); const customerMap = new Map((customers.data ?? []).map((item) => [item.id, item])); const propertyMap = new Map((properties.data ?? []).map((item) => [item.id, item])); const quoteMap = new Map((quotes.data ?? []).map((item) => [item.id, item])); return jobs.flatMap((item) => { const customer = customerMap.get(item.customer_id); const property = propertyMap.get(item.property_id); return customer && property ? [{ ...item, customer, property, quote: item.quote_id ? quoteMap.get(item.quote_id) ?? null : null }] : []; }); }

export async function getJobs(organizationId: string, filters: { search?: string; status?: string; payment?: string; installDate?: string; takedownDate?: string } = {}) { const supabase = await createSupabaseServerClient(); let query = supabase.from("jobs").select("*").eq("organization_id", organizationId); if (filters.status) query = query.eq("status", filters.status); if (filters.payment) query = query.eq("payment_status", filters.payment); if (filters.installDate) query = query.eq("install_date", filters.installDate); if (filters.takedownDate) query = query.eq("takedown_date", filters.takedownDate); const { data, error } = await query.order("install_date", { ascending: true, nullsFirst: false }).order("created_at", { ascending: false }); if (error) throw new Error("We could not load jobs."); let records = await attach(organizationId, data ?? []); const search = filters.search?.trim().toLocaleLowerCase(); if (search) records = records.filter((item) => [item.job_number, item.customer.first_name, item.customer.last_name, item.property.property_name, item.property.address_line_1, item.property.city].filter(Boolean).join(" ").toLocaleLowerCase().includes(search)); return records; }
export async function getJob(organizationId: string, jobId: string): Promise<JobRecord | null> { const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("jobs").select("*").eq("organization_id", organizationId).eq("id", jobId).maybeSingle(); if (error) throw new Error("We could not load that job."); if (!data) return null; const [record] = await attach(organizationId, [data]); if (!record?.quote) return null; const { data: lines, error: lineError } = data.quote_id ? await supabase.from("quote_line_items").select("*").eq("organization_id", organizationId).eq("quote_id", data.quote_id).eq("customer_visible", true).order("created_at") : { data: [], error: null }; if (lineError) throw new Error("We could not load job materials."); return { ...record, quote: record.quote, line_items: lines ?? [] }; }
export async function getJobForQuote(organizationId: string, quoteId: string) { const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("jobs").select("*").eq("organization_id", organizationId).eq("quote_id", quoteId).maybeSingle(); if (error) throw new Error("We could not check the related job."); if (!data) return null; const [record] = await attach(organizationId, [data]); return record ?? null; }
export async function getJobsForCustomer(organizationId: string, customerId: string) { const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("jobs").select("*").eq("organization_id", organizationId).eq("customer_id", customerId).order("created_at", { ascending: false }); if (error) throw new Error("We could not load customer jobs."); return attach(organizationId, data ?? []); }
export async function getJobsForProperty(organizationId: string, propertyId: string) { const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("jobs").select("*").eq("organization_id", organizationId).eq("property_id", propertyId).order("created_at", { ascending: false }); if (error) throw new Error("We could not load property jobs."); return attach(organizationId, data ?? []); }
