import "server-only";
import { paymentTotal } from "@/lib/payment-options";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { Payment } from "@/types/database";
export interface PaymentSummary { payments: Payment[]; totalPaid: number; remainingBalance: number; }
export async function getPaymentsForJob(organizationId: string, jobId: string, quoteTotal: string | number): Promise<PaymentSummary> { const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("payments").select("*").eq("organization_id", organizationId).eq("job_id", jobId).order("payment_date", { ascending: false }).order("created_at", { ascending: false }); if (error) throw new Error("We could not load payment history."); const payments = data ?? []; const totalPaid = paymentTotal(payments); return { payments, totalPaid, remainingBalance: Math.max(0, Number(quoteTotal) - totalPaid) }; }
export async function getPayment(organizationId: string, paymentId: string) { const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("payments").select("*").eq("organization_id", organizationId).eq("id", paymentId).maybeSingle(); if (error) throw new Error("We could not load that payment."); return data; }
export async function getPaymentsForCustomer(organizationId: string, customerId: string) { const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("payments").select("*").eq("organization_id", organizationId).eq("customer_id", customerId).order("payment_date", { ascending: false }).limit(20); if (error) throw new Error("We could not load customer payments."); return data ?? []; }
export async function getPaymentTotalsByJob(organizationId: string, jobIds: string[]) { if (!jobIds.length) return new Map<string, number>(); const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("payments").select("job_id, amount, payment_type, status").eq("organization_id", organizationId).in("job_id", jobIds); if (error) throw new Error("We could not load job payment totals."); const groups = new Map<string, Array<{ amount: string; payment_type: string; status: string }>>(); for (const item of data ?? []) { if (!item.job_id) continue; groups.set(item.job_id, [...(groups.get(item.job_id) ?? []), item]); } return new Map([...groups].map(([jobId, payments]) => [jobId, paymentTotal(payments)])); }
