import Link from "next/link";
import { ArrowLeft, Pencil, Plus, ReceiptText } from "lucide-react";
import { notFound } from "next/navigation";
import { JobQuickAction } from "@/components/jobs/job-actions";
import { JobMaterialsSection } from "@/components/materials/job-materials-section";
import { FileSection } from "@/components/files/file-section";
import { DeletePaymentForm } from "@/components/payments/payment-actions";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { LinkButton } from "@/components/ui/link-button";
import { PageHeader } from "@/components/ui/page-header";
import { requireOrganization } from "@/lib/auth/current";
import { customerName, propertyAddress } from "@/lib/format";
import { jobStatusLabel, paymentStatusLabel } from "@/lib/job-options";
import { getJob } from "@/lib/jobs";
import { optionLabel, paymentRecordStatuses, paymentTypes } from "@/lib/payment-options";
import { getPaymentsForJob } from "@/lib/payments";
import { getScheduleEventsForJob } from "@/lib/schedule";
const money = (value: string | number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value));
function Note({ label, value }: { label: string; value: string | null }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{value || "No notes added."}</p></div>; }

export default async function JobDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ created?: string; updated?: string; status?: string; payment?: string }> }) {
  const { organization } = await requireOrganization(); const { id } = await params; const notice = await searchParams; const job = await getJob(organization.id, id); if (!job) notFound(); const [summary, scheduleEvents] = await Promise.all([getPaymentsForJob(organization.id, id, job.quote?.total ?? 0), getScheduleEventsForJob(organization.id, id)]); const message = notice.created ? "Job created and schedule updated." : notice.updated ? "Job changes saved." : notice.status ? "Job status updated." : notice.payment === "added" ? "Payment recorded." : notice.payment === "updated" ? "Payment changes saved." : notice.payment === "deleted" ? "Payment deleted and balance recalculated." : null;
  return <div className="space-y-7"><LinkButton href="/jobs" size="sm" variant="ghost"><ArrowLeft className="mr-2 size-4" />Back to Jobs</LinkButton><PageHeader title={job.job_number || "Job"} description={`${customerName(job.customer.first_name, job.customer.last_name)} · ${job.property.property_name || propertyAddress(job.property)}`} actions={<div className="flex flex-wrap gap-2"><LinkButton href={`/jobs/${id}/invoice`} variant="secondary"><ReceiptText className="mr-2 size-4" />View Invoice</LinkButton><LinkButton href={`/jobs/${id}/payments/new`}><Plus className="mr-2 size-4" />Record Payment</LinkButton><LinkButton href={`/jobs/${id}/edit`} variant="secondary"><Pencil className="mr-2 size-4" />Edit Job</LinkButton></div>} />{message ? <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{message}</div> : null}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]"><div className="space-y-6"><Card><CardHeader><div className="flex flex-wrap items-center gap-2"><Badge>{jobStatusLabel(job.status)}</Badge><Badge variant={job.payment_status === "paid" ? "success" : "warning"}>{paymentStatusLabel(job.payment_status)}</Badge></div></CardHeader><CardContent className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs font-bold uppercase text-slate-500">Customer</p><Link href={`/customers/${job.customer_id}`} className="mt-2 block font-semibold text-amber-800">{customerName(job.customer.first_name, job.customer.last_name)}</Link></div><div><p className="text-xs font-bold uppercase text-slate-500">Property</p><Link href={`/properties/${job.property_id}`} className="mt-2 block font-semibold text-amber-800">{propertyAddress(job.property)}</Link></div><div><p className="text-xs font-bold uppercase text-slate-500">Quote</p>{job.quote ? <Link href={`/quotes/${job.quote.id}`} className="mt-2 block font-semibold text-amber-800">{job.quote.quote_number}</Link> : <p className="mt-2">Not linked</p>}</div></CardContent></Card><Card><CardHeader><h2 className="font-bold">Schedule</h2></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase text-slate-500">Install Date</p><p className="mt-2 font-semibold">{job.install_date || "Not scheduled"}</p><p className="mt-1 text-sm text-slate-500">{job.install_time_window || "Time window not set"}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Takedown Date</p><p className="mt-2 font-semibold">{job.takedown_date || "Not scheduled"}</p><p className="mt-1 text-sm text-slate-500">{job.takedown_time_window || "Time window not set"}</p></div></CardContent></Card><Card><CardHeader><h2 className="font-bold">Work and Materials Summary</h2></CardHeader><CardContent className="p-0"><div className="divide-y">{job.line_items.map((item) => <div key={item.id} className="grid gap-2 p-4 sm:grid-cols-[minmax(0,1fr)_120px_120px]"><div><p className="font-semibold">{item.description}</p>{item.notes ? <p className="mt-1 text-xs text-slate-500">{item.notes}</p> : null}</div><p className="text-sm">{Number(item.quantity)} {item.unit}</p><p className="text-right font-bold">{money(item.line_total)}</p></div>)}</div></CardContent></Card>
      <Card><CardHeader><div className="flex items-center justify-between"><div><h2 className="font-bold">Payments</h2><p className="mt-1 text-sm text-slate-500">Manual payment history for this job.</p></div><LinkButton href={`/jobs/${id}/payments/new`} size="sm"><Plus className="mr-2 size-4" />Record Payment</LinkButton></div></CardHeader><CardContent className="p-0">{summary.payments.length ? <div className="divide-y">{summary.payments.map((payment) => <div key={payment.id} className="grid gap-3 p-4 sm:grid-cols-[120px_minmax(0,1fr)_120px_120px_auto] sm:items-center"><div><p className="text-sm font-semibold">{payment.payment_date?.slice(0, 10) || "No date"}</p><p className="mt-1 text-xs text-slate-500">{payment.payment_method || "Method not set"}</p></div><div><p className="font-semibold">{optionLabel(paymentTypes, payment.payment_type)}</p><p className="mt-1 line-clamp-1 text-xs text-slate-500">{payment.reference_number || payment.notes || "No reference"}</p></div><p className="font-bold">{payment.payment_type === "refund" ? "−" : ""}{money(payment.amount)}</p><Badge variant={payment.status === "paid" ? "success" : "neutral"}>{optionLabel(paymentRecordStatuses, payment.status)}</Badge><div className="flex gap-1"><LinkButton href={`/payments/${payment.id}/edit`} size="sm" variant="ghost">Edit</LinkButton><DeletePaymentForm paymentId={payment.id} /></div></div>)}</div> : <div className="p-4"><EmptyState compact title="No payments recorded" description="Record the deposit or another received payment to update the balance." actionLabel="Record Payment" actionHref={`/jobs/${id}/payments/new`} /></div>}</CardContent></Card>
      <Card><CardHeader><h2 className="font-bold">Job Notes</h2></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2"><Note label="Crew Notes" value={job.crew_notes} /><Note label="Materials Notes" value={job.materials_notes} /><Note label="Storage Notes" value={job.storage_notes} /><Note label="Internal Notes" value={job.internal_notes} /></CardContent></Card></div>
      <div className="space-y-6"><Card><CardHeader><h2 className="font-bold">Financial Summary</h2></CardHeader><CardContent className="space-y-3">{job.quote ? <><div className="flex justify-between"><span>Job Total</span><strong>{money(job.quote.total)}</strong></div><div className="flex justify-between"><span>Deposit Required</span><strong>{money(job.quote.deposit_required)}</strong></div><div className="flex justify-between"><span>Total Paid</span><strong className="text-emerald-700">{money(summary.totalPaid)}</strong></div><div className="flex justify-between border-t pt-3 text-lg"><span>Balance Due</span><strong>{money(summary.remainingBalance)}</strong></div></> : <p className="text-sm text-slate-500">Quote totals unavailable.</p>}<Badge variant={summary.remainingBalance <= 0 ? "success" : "warning"}>{summary.remainingBalance <= 0 ? "Paid" : `Balance Due: ${money(summary.remainingBalance)}`}</Badge></CardContent></Card><Card><CardHeader><h2 className="font-bold">Quick Job Updates</h2></CardHeader><CardContent className="flex flex-col items-start gap-3"><JobQuickAction jobId={id} status="scheduled" label="Mark Scheduled" /><JobQuickAction jobId={id} status="materials_ready" label="Mark Materials Ready" /><JobQuickAction jobId={id} status="installed" label="Mark Installed" /><JobQuickAction jobId={id} status="takedown_complete" label="Mark Takedown Complete" /><JobQuickAction jobId={id} status="complete" label="Mark Complete" /><JobQuickAction jobId={id} status="canceled" label="Cancel Job" /></CardContent></Card><Card><CardHeader><h2 className="font-bold">Related Links</h2></CardHeader><CardContent className="space-y-2"><LinkButton href={`/customers/${job.customer_id}`} variant="ghost" className="w-full">Customer</LinkButton><LinkButton href={`/properties/${job.property_id}`} variant="ghost" className="w-full">Property</LinkButton>{job.quote ? <><LinkButton href={`/quotes/${job.quote.id}`} variant="ghost" className="w-full">Quote</LinkButton>{job.quote.site_visit_id ? <LinkButton href={`/site-visits/${job.quote.site_visit_id}`} variant="ghost" className="w-full">Site Visit</LinkButton> : null}</> : null}</CardContent></Card></div></div>
    <Card><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">Install &amp; Takedown Schedule</h2><p className="mt-1 text-sm text-slate-500">Job dates automatically create or update matching schedule events.</p></div><LinkButton href={`/jobs/${id}/edit`} variant="secondary">{job.install_date && job.takedown_date ? "Reschedule" : "Schedule Work"}</LinkButton></div></CardHeader><CardContent>{scheduleEvents.length ? <div className="grid gap-3 sm:grid-cols-2">{scheduleEvents.map((event) => <div key={event.id} className="rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between gap-2"><Badge>{event.event_type.replaceAll("_", " ")}</Badge><Badge variant={event.status === "completed" ? "success" : "neutral"}>{event.status}</Badge></div><p className="mt-3 font-bold">{event.event_date}</p><p className="mt-1 text-sm text-slate-600">{event.time_window || event.start_time?.slice(0, 5) || "Time to be set"}</p><LinkButton href={`/schedule/${event.id}/edit`} size="sm" variant="ghost" className="mt-3">Edit Event</LinkButton></div>)}</div> : <p className="text-sm text-slate-500">No install or takedown events yet. Add dates to schedule this job.</p>}</CardContent></Card>
    <JobMaterialsSection organizationId={organization.id} jobId={id} />
    <FileSection organizationId={organization.id} relatedType="jobs" relatedId={id} photoTypes={["Before install", "Finished install", "Materials loaded", "Outlet/timer", "Takedown", "Storage", "Damage/safety issue", "Other"]} emptyText="No job photos yet. Add before, after, takedown, or storage photos." />
  </div>;
}
