import { Eye, Pencil, Ruler } from "lucide-react";
import { DeleteMeasurementForm } from "@/components/measurements/delete-measurement-form";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { LinkButton } from "@/components/ui/link-button";
import type { MeasurementListItem } from "@/lib/measurements";

export function MeasurementCard({ measurement, allowDelete = false }: { measurement: MeasurementListItem; allowDelete?: boolean }) {
  return <Card><CardContent className="space-y-4 p-4"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-cyan-100 text-cyan-700"><Ruler className="size-5" /></span><div className="min-w-0"><h3 className="font-bold text-slate-950">{measurement.zone_name}</h3><p className="mt-1 text-sm text-slate-600">{measurement.measurement_type} · {Number(measurement.quantity).toLocaleString("en-US", { maximumFractionDigits: 2 })} {measurement.unit}</p><p className="mt-1 text-xs text-slate-500">{measurement.catalog_item?.name || "No catalog item"}</p></div></div><Badge variant={measurement.included_in_quote ? "success" : "neutral"}>{measurement.included_in_quote ? "In quote" : "Excluded"}</Badge></div><div className="grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-3 text-xs"><div><p className="font-bold uppercase text-slate-500">Height</p><p className="mt-1 text-slate-800">{measurement.height_level || "Not set"}</p></div><div><p className="font-bold uppercase text-slate-500">Difficulty</p><p className="mt-1 text-slate-800">{measurement.difficulty || "Normal"} · {Number(measurement.difficulty_multiplier).toLocaleString("en-US", { maximumFractionDigits: 2 })}×</p></div></div>{measurement.notes ? <p className="line-clamp-2 text-sm text-slate-600">{measurement.notes}</p> : null}<div className="flex flex-wrap gap-2"><LinkButton href={`/measurements/${measurement.id}`} variant="secondary" size="sm"><Eye className="mr-1.5 size-3.5" />View</LinkButton><LinkButton href={`/measurements/${measurement.id}/edit`} variant="ghost" size="sm"><Pencil className="mr-1.5 size-3.5" />Edit</LinkButton>{allowDelete ? <DeleteMeasurementForm measurementId={measurement.id} zoneName={measurement.zone_name} compact /> : null}</div></CardContent></Card>;
}
