import Link from "next/link";
import { ArrowLeft, Eye, Pencil } from "lucide-react";
import { notFound } from "next/navigation";
import { CopyProposalLink, GenerateProposalLinkForm, MarkProposalSentForm } from "@/components/proposals/proposal-controls";
import { FileSection } from "@/components/files/file-section";
import { DeleteDraftQuoteForm, QuoteStatusForm } from "@/components/quotes/quote-actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { LinkButton } from "@/components/ui/link-button";
import { PageHeader } from "@/components/ui/page-header";
import { requireOrganization } from "@/lib/auth/current";
import { customerName, formatDate, propertyAddress } from "@/lib/format";
import { getPackage } from "@/lib/packages";
import { getJobForQuote } from "@/lib/jobs";
import { paymentStatusLabel } from "@/lib/job-options";
import { getPaymentsForJob } from "@/lib/payments";
import { getQuote } from "@/lib/quotes";

const money = (value: string | number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value));
const tracked = (value: string | null) => value ? formatDate(value) : "Not yet";
function Note({ title, value }: { title: string; value: string | null }) { return <div><p className="text-xs font-bold uppercase text-slate-500">{title}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{value || "Not provided"}</p></div>; }

export default async function QuoteDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ created?: string; updated?: string; status?: string; proposal?: string }> }) {
  const { organization } = await requireOrganization(); const { id } = await params; const notice = await searchParams; const quote = await getQuote(organization.id, id); if (!quote) notFound(); const [packageRecord, relatedJob] = await Promise.all([quote.package_id ? getPackage(organization.id, quote.package_id) : null, getJobForQuote(organization.id, id)]); const paymentSummary = relatedJob ? await getPaymentsForJob(organization.id, relatedJob.id, quote.total) : null; const message = notice.created ? "Quote created." : notice.updated ? "Quote updated." : notice.proposal === "ready" ? "Proposal link generated." : notice.status ? `Quote marked ${notice.status}.` : null;
  return <div className="space-y-7"><LinkButton href="/quotes" size="sm" variant="ghost"><ArrowLeft className="mr-2 size-4" />Back to Quotes</LinkButton><PageHeader title={quote.quote_number || "Quote"} description={`${customerName(quote.customer.first_name, quote.customer.last_name)} · ${quote.property.property_name || propertyAddress(quote.property)}`} actions={<div className="flex flex-wrap gap-2"><LinkButton href={`/quotes/${id}/proposal`} variant="secondary"><Eye className="mr-2 size-4" />Preview Proposal</LinkButton><LinkButton href={`/quotes/${id}/edit`}><Pencil className="mr-2 size-4" />Edit Quote</LinkButton></div>} />
    {message ? <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{message}</div> : null}
    <Card className={quote.status === "approved" ? "border-emerald-200 bg-emerald-50/40" : ""}><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-slate-950">Installation Job</h2><p className="mt-1 text-sm text-slate-600">{relatedJob ? `${relatedJob.job_number} is connected to this quote.` : quote.status === "approved" ? "This approved quote is ready to schedule as a job." : "Quote must be approved before converting to a job."}</p>{paymentSummary ? <p className="mt-2 text-sm font-semibold text-slate-800">Total paid: {money(paymentSummary.totalPaid)} · Remaining balance: {money(paymentSummary.remainingBalance)} · {paymentStatusLabel(relatedJob!.payment_status)}</p> : !relatedJob ? <p className="mt-2 text-xs text-slate-500">Convert this approved quote to a job before recording payments.</p> : null}</div>{relatedJob ? <LinkButton href={`/jobs/${relatedJob.id}`}>View Job</LinkButton> : quote.status === "approved" ? <LinkButton href={`/quotes/${id}/convert-to-job`}>Convert to Job</LinkButton> : <Button type="button" disabled>Convert to Job</Button>}</CardContent></Card>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]"><Card><CardHeader className="flex flex-row items-center justify-between"><div><h2 className="font-bold text-slate-950">Quote Details</h2><p className="mt-1 text-sm text-slate-500">Created {formatDate(quote.created_at)}</p></div><Badge className="capitalize" variant={quote.status === "approved" ? "success" : quote.status === "declined" || quote.status === "expired" ? "danger" : "neutral"}>{quote.status}</Badge></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase text-slate-500">Customer</p><Link href={`/customers/${quote.customer_id}`} className="mt-2 block font-semibold text-amber-800">{customerName(quote.customer.first_name, quote.customer.last_name)}</Link></div><div><p className="text-xs font-bold uppercase text-slate-500">Property</p><Link href={`/properties/${quote.property_id}`} className="mt-2 block font-semibold text-amber-800">{propertyAddress(quote.property)}</Link></div><div><p className="text-xs font-bold uppercase text-slate-500">Site Visit</p>{quote.site_visit_id ? <Link href={`/site-visits/${quote.site_visit_id}`} className="mt-2 block font-semibold text-amber-800">View site visit</Link> : <p className="mt-2 text-sm">Not selected</p>}</div><div><p className="text-xs font-bold uppercase text-slate-500">Package</p><p className="mt-2 font-semibold">{quote.package?.name || "Custom quote"}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Quote Date</p><p className="mt-2 text-sm">{quote.quote_date}</p></div><div><p className="text-xs font-bold uppercase text-slate-500">Expiration Date</p><p className="mt-2 text-sm">{quote.expiration_date || "Not set"}</p></div></CardContent></Card><Card><CardHeader><h2 className="font-bold text-slate-950">Quote Actions</h2></CardHeader><CardContent className="space-y-3"><QuoteStatusForm quoteId={id} status="approved" /><QuoteStatusForm quoteId={id} status="declined" /><LinkButton href={`/quotes/${id}/edit`} variant="secondary" className="w-full">Edit Quote</LinkButton>{quote.status === "draft" ? <div className="border-t pt-4"><DeleteDraftQuoteForm quoteId={id} /></div> : null}</CardContent></Card></div>
    <Card><CardHeader><h2 className="font-bold text-slate-950">Customer Proposal</h2><p className="mt-1 text-sm text-slate-500">Preview, share, and track the customer-facing proposal.</p></CardHeader><CardContent className="space-y-5"><div className="flex flex-wrap gap-2"><LinkButton href={`/quotes/${id}/proposal`}><Eye className="mr-2 size-4" />Preview Proposal</LinkButton><MarkProposalSentForm quoteId={id} /></div>{quote.proposal_token ? <CopyProposalLink token={quote.proposal_token} /> : <GenerateProposalLinkForm quoteId={id} />}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Sent", tracked(quote.proposal_sent_at)], ["Viewed", tracked(quote.proposal_viewed_at)], ["Approved", tracked(quote.approved_at)], ["Declined", tracked(quote.declined_at)]].map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div>{quote.customer_approval_name ? <p className="text-sm text-slate-600">Approved by <strong>{quote.customer_approval_name}</strong>{quote.customer_approval_email ? ` · ${quote.customer_approval_email}` : ""}</p> : null}{quote.customer_decline_reason ? <p className="rounded-xl bg-red-50 p-3 text-sm text-red-900"><strong>Decline reason:</strong> {quote.customer_decline_reason}</p> : null}</CardContent></Card>
    {packageRecord ? <Card><CardHeader><h2 className="font-bold text-slate-950">Included with {packageRecord.name}</h2><p className="mt-1 text-sm text-slate-500">Reference only—the package base price is shown as one priced line.</p></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{packageRecord.items.filter((item) => item.included).map((item) => <div key={item.id} className="rounded-xl bg-slate-50 p-3"><p className="font-semibold text-slate-950">{item.catalog_item.name}</p><p className="mt-1 text-xs text-slate-500">{Number(item.quantity)} {item.unit}{item.notes ? ` · ${item.notes}` : ""}</p></div>)}</CardContent></Card> : null}
    <Card><CardHeader><div className="flex items-center justify-between"><h2 className="font-bold text-slate-950">Line Items</h2><LinkButton href={`/quotes/${id}/edit`} size="sm" variant="secondary">Add Line Item</LinkButton></div></CardHeader><CardContent className="p-0"><div className="divide-y">{quote.line_items.map((item) => <div key={item.id} className="grid gap-3 p-4 sm:grid-cols-[minmax(0,1fr)_90px_100px_90px_120px] sm:items-center"><div><p className="font-semibold text-slate-950">{item.description}</p><p className="mt-1 text-xs text-slate-500">{item.notes || (item.customer_visible ? "Customer visible" : "Internal line")}</p></div><p className="text-sm">{Number(item.quantity)} {item.unit}</p><p className="text-sm">{money(item.unit_price)}</p><p className="text-sm">× {Number(item.multiplier)}</p><p className="text-right font-bold">{money(item.line_total)}</p></div>)}</div></CardContent></Card>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><Card><CardHeader><h2 className="font-bold text-slate-950">Notes and Terms</h2></CardHeader><CardContent className="space-y-6"><Note title="Customer Notes" value={quote.customer_notes} /><Note title="Terms" value={quote.terms} /><Note title="Internal Notes" value={quote.internal_notes} /></CardContent></Card><Card><CardHeader><h2 className="font-bold text-slate-950">Totals</h2></CardHeader><CardContent className="space-y-3"><div className="flex justify-between"><span>Subtotal</span><strong>{money(quote.subtotal)}</strong></div><div className="flex justify-between"><span>Discount</span><strong>− {money(quote.discount)}</strong></div><div className="flex justify-between border-t pt-3 text-lg"><span>Total</span><strong>{money(quote.total)}</strong></div><div className="flex justify-between"><span>Deposit Required</span><strong>{money(quote.deposit_required)}</strong></div><div className="flex justify-between"><span>Balance Due</span><strong>{money(quote.balance_due)}</strong></div><p className="text-xs text-slate-500">Deposit: {quote.deposit_type === "percentage" ? `${Number(quote.deposit_value)}%` : money(quote.deposit_value)}</p></CardContent></Card></div>
    <FileSection organizationId={organization.id} relatedType="quotes" relatedId={id} photoTypes={["Proposal/mockup", "Customer inspiration", "Design reference", "Other"]} emptyText="No quote files yet. Add proposal mockups, inspiration, or design references." helperText="Quote files stay internal unless you explicitly mark them customer-facing." />
  </div>;
}
