import { notFound } from "next/navigation";
import { ArrowLeft, Boxes, DollarSign, MapPin, Pencil, TriangleAlert } from "lucide-react";
import { CatalogStatusForm, DeleteCatalogItemForm } from "@/components/catalog/catalog-actions";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { LinkButton } from "@/components/ui/link-button";
import { PageHeader } from "@/components/ui/page-header";
import { requireOrganization } from "@/lib/auth/current";
import { catalogNumbers, getCatalogItem, pricingMethodLabel } from "@/lib/catalog";
import { formatDate } from "@/lib/format";

const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);
function Detail({ label, value }: { label: string; value?: string | null }) { return <div className="rounded-xl bg-slate-50 p-4"><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-sm font-semibold leading-6 text-slate-900">{value || "Not provided"}</dd></div>; }

export default async function CatalogItemDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ created?: string; updated?: string; status?: string }> }) {
  const { organization } = await requireOrganization(); const { id } = await params; const notice = await searchParams; const item = await getCatalogItem(organization.id, id); if (!item) notFound(); const numbers = catalogNumbers(item);
  return <div className="space-y-7"><PageHeader title={item.name} description={`${item.category} · ${pricingMethodLabel(item.pricing_method)} per ${item.unit_type}`} actions={<div className="flex flex-wrap gap-2"><LinkButton href="/catalog" variant="secondary"><ArrowLeft className="mr-2 size-4" />Catalog</LinkButton><LinkButton href={`/catalog/${id}/edit`}><Pencil className="mr-2 size-4" />Edit Item</LinkButton></div>} />
    {notice.created === "1" ? <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">Catalog item added.</div> : null}{notice.updated === "1" ? <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">Catalog item changes saved.</div> : null}{notice.status ? <div role="status" className="rounded-xl border border-sky-200 bg-sky-50 px-4 py-3 text-sm font-medium text-sky-800">Item {notice.status === "active" ? "reactivated" : "deactivated"}.</div> : null}
    {numbers.lowStock ? <div role="alert" className="flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800"><TriangleAlert className="size-5" />Low stock: {numbers.remaining} {item.unit_type} remaining, with reorder set at {numbers.threshold}.</div> : null}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]"><Card><CardHeader className="flex flex-row items-center justify-between gap-3"><h2 className="font-bold text-slate-950">Item Details</h2><div className="flex gap-2"><Badge variant={item.active ? "success" : "neutral"}>{item.active ? "Active" : "Inactive"}</Badge><Badge>{item.customer_facing ? "Customer-facing" : "Internal"}</Badge></div></CardHeader><CardContent className="space-y-4"><dl className="grid gap-4 sm:grid-cols-2"><Detail label="Description" value={item.description} /><Detail label="Category" value={item.category} /><Detail label="Pricing method" value={pricingMethodLabel(item.pricing_method)} /><Detail label="Unit type" value={item.unit_type} /><Detail label="Unit price" value={money(numbers.unitPrice)} /><Detail label="Cost" value={money(numbers.cost)} /><Detail label="Estimated margin" value={money(numbers.margin)} /><Detail label="Storage location" value={item.storage_location} /><div className="sm:col-span-2"><Detail label="Notes" value={item.notes} /></div></dl><div className="grid gap-1 border-t border-slate-100 pt-4 text-xs text-slate-500 sm:grid-cols-2"><p>Created {formatDate(item.created_at)}</p><p className="sm:text-right">Updated {formatDate(item.updated_at)}</p></div></CardContent></Card>
      <div className="space-y-6"><Card><CardHeader><h2 className="font-bold text-slate-950">Inventory</h2></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-3"><Detail label="Available" value={String(numbers.available)} /><Detail label="Reserved" value={String(numbers.reserved)} /><Detail label="Remaining" value={String(numbers.remaining)} /><Detail label="Reorder threshold" value={String(numbers.threshold)} /></div><div className="flex flex-wrap gap-2"><Badge variant={item.track_inventory ? "success" : "neutral"}>{item.track_inventory ? "Inventory tracked" : "Not tracked"}</Badge>{item.track_inventory ? <Badge variant={numbers.lowStock ? "danger" : "success"}>{numbers.lowStock ? "Low stock" : "Stock level okay"}</Badge> : null}</div></CardContent></Card><Card><CardHeader><h2 className="font-bold text-slate-950">Item Actions</h2></CardHeader><CardContent className="space-y-4"><LinkButton href={`/catalog/${id}/edit`} className="w-full"><Pencil className="mr-2 size-4" />Edit Item</LinkButton><CatalogStatusForm itemId={id} active={item.active} /><div className="border-t border-slate-100 pt-4"><p className="mb-3 text-xs leading-5 text-slate-500">Items already used by measurements, packages, or quotes cannot be deleted. Deactivate them instead.</p><DeleteCatalogItemForm itemId={id} itemName={item.name} /></div></CardContent></Card></div></div>
  </div>;
}
